### PR TITLE
Update release workflow

### PR DESCRIPTION
**Pull request by gastaldi**
- As needed in https://github.com/quarkiverse/quarkiverse-devops/issues/210

### CODE REVIEW

**Comment by jesuino** [comment]
Sorry, I changed it because I was having an exception during build. Now we will have a release soon with Dashbuilder 0.32.0, which will be using this new workflow

**Comment by jesuino** [comment]
Hello @gastaldi 

After the merge the release fails with this:

```
Error: [ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.3.0:enforce (enforce-java-version) on project quarkus-dashbuilder-parent: 
Error: [ERROR] Rule 1: org.apache.maven.enforcer.rules.version.RequireJavaVersion failed with message:
Error: [ERROR] To build this project JDK 17 (or greater) is required. Please install it.
Error: [ERROR] -> [Help 1]
Error: [ERROR] 
Error: [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
Error: [ERROR] Re-run Maven using the -X switch to enable full debug logging.
Error: [ERROR] 
Error: [ERROR] For more information about the errors and possible solutions, please read the following articles:
Error: [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

Do you know if I should update somewhere else? I also modified the build to use Java 17.

Thanks!

**Comment by gastaldi** [comment]
@jesuino my bad, https://github.com/quarkiverse/quarkus-dashbuilder/commit/dac71e239c2d3126c7f5b5e8b2efe20d0592bfde fixes it

**Comment by jesuino** [comment]
np at all, Thanks!

**Pull request merged**
